public class ArrayIndexOutOfBoundsExceptionHandling {

    public static void main(String[] args) {
        try {
            // a) Accessing an array element outside its bound
            int[] arr = {1, 2, 3};
            int element = arr[3];
            System.out.println("Element at index 3: " + element);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }

        try {
            // b) Iterating beyond the array length
            int[] arr = {1, 2, 3};
            for (int i = 0; i <= arr.length; i++) {
                System.out.println("Element at index " + i + ": " + arr[i]);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }

        try {
            // c) Nested array and incorrect index
            int[][] nestedArr = {{1, 2, 3}, {4, 5, 6}};
            int element = nestedArr[1][3];
            System.out.println("Element at index [1][3]: " + element);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }

        try {
            // d) Passing incorrect array to the method
            int[] arr = {1, 2, 3};
            printArray(arr, 4);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    // Method to demonstrate passing incorrect array to the method
    public static void printArray(int[] arr, int index) {
        System.out.println("Element at index " + index + ": " + arr[index]);
    }
}
